name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * 1"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          repositories_affiliations: owner, collaborator, organization_member
          config_padding: 5%          
          token: ${{ secrets.METRICS_TOKEN }}
          
          user: egallis31
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Denver
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
